--static void defenem(en&env){ob*enem=env.obs.get("enem");
--enem->spr=env.sps.get("sp1");
--enem->oeadd(ALRM,0,[](in*i){i->hsp*=-1;i->alrn[0]=40;});
--enem->oeadd(ALRM,1,[](in*i){en&env=eget();
--in*ship0=(*env.obs.get("ship"))[0];
--double nx=i->x+arb(100)-50,ny=i->y+arb(100)-50;
--REPEAT(3){
--in*bull0=env.obs.get("bull")->oiadd(nx,ny);
--if(ship0) bull0->dir=point_direction(nx,ny,ship0->x,ship0->y);
--bull0->spe=arb(8)+4;
--}
--i->alrn[1]=3;
--});
--enem->oeadd(ALRM,2,[](in*i){
--in*bull1=instance_create(eget(),"bull1",i->x,i->y);
--bull1->alrn[0]=30;
--bull1->dir=180+arb(180);
--bull1->spe=4;
--i->alrn[2]=30;
--});
